In [1]:
import pandas as pd
import uuid

path = 'C:/Users/Mr. Grinch/Downloads/Data/acs2017_census_tract_data.csv'

df = pd.read_csv(path, usecols=['State', 'County', 'TotalPop', 'Poverty', 'IncomePerCap'])

# Calculate total income for each region
df['povertyWeighted'] = df['Poverty'] * df['TotalPop']
df['TotalIncome'] = df['IncomePerCap'] * df['TotalPop']


county_info1 = df.groupby('County').agg({
    'State': 'first',
    'TotalPop': 'sum',
    'Poverty': 'sum',
    'TotalIncome': 'sum',
    'povertyWeighted' : 'sum'
}).reset_index()

county_info1['povertyPercent'] = county_info1['povertyWeighted'] / county_info1['TotalPop']

county_info1['IncomePerCap'] = county_info1['TotalIncome'] / county_info1['TotalPop']

county_info1 = county_info1.drop(columns=['TotalIncome', 'povertyWeighted', 'Poverty'])

county_info2 = county_info1.sort_values(by='State')

county_info3 = county_info2.assign(ID=lambda x: [uuid.uuid4() for _ in range(len(x))])


county_info3

,County,State,TotalPop,povertyPercent,IncomePerCap,ID
1602,Shelby County,Alabama,1351091,17.665535,29089.787526,0ea22b47-f8f6-414e-9316-bb4706118610
261,Calhoun County,Alabama,349416,18.232007,23653.098667,5f8ee9cc-ef17-46ad-aa97-39435722111c
457,Cullman County,Alabama,81703,16.334966,21857.098858,df50ec61-f095-49c2-920e-127023cf05e4
605,Fayette County,Alabama,778337,16.576727,29656.115084,18b74795-ad23-4635-a90c-801e83936f92
246,Butler County,Alabama,726560,13.022608,29987.615836,e56cd387-8902-4976-9d0b-9cdbb1ffd6b1
...,...,...,...,...,...,...
1784,Uinta County,Wyoming,20758,14.821438,27114.842808,e07c6c07-ac37-44e4-ba93-52fa32f17d23
992,Laramie County,Wyoming,97031,10.378440,31554.456761,2574030d-54b2-465b-8fdc-cc04e2cdf771
1703,Sweetwater County,Wyoming,44527,12.079610,31699.951737,dee7b094-3a4f-4041-be6c-e20858fc23bd
823,Hot Springs County,Wyoming,4741,12.482936,30938.712508,5a5138d9-a630-4e19-81d8-ed18aa0b6c04
1227,Natrona County,Wyoming,81023,9.880091,31899.670550,453bccbc-9242-4308-ac6c-58277d6bb626

In [2]:
def search_county(county_name):
    return county_info3[county_info3['County'] == county_name]

loudoun_info = search_county('Loudoun County')
print(loudoun_info)

washington_info = search_county('Washington County')
print(washington_info)

harlan_info = search_county('Harlan County')
print(harlan_info)

malheur_info = search_county('Malheur County')
print(malheur_info)

              County     State  TotalPop  povertyPercent  IncomePerCap  \
1048  Loudoun County  Virginia    374558        3.689598  50455.645745

                                        ID
1048  7ee79381-a25e-44cf-a285-6c1bd9ddafe9
                 County    State  TotalPop  povertyPercent  IncomePerCap  \
1851  Washington County  Alabama   2564646        12.49138  31477.494308

                                        ID
1851  f1d03149-51ef-4293-936d-56d92a1de0e3
            County     State  TotalPop  povertyPercent  IncomePerCap  \
764  Harlan County  Kentucky     31017         33.1229  16678.064062

                                       ID
764  d6440a57-4a36-436a-981f-28aa39536a96
              County   State  TotalPop  povertyPercent  IncomePerCap  \
1080  Malheur County  Oregon     30421       24.298225  17567.504323

                                        ID
1080  81271b91-ed82-4898-9cc5-03d3a324663b

In [3]:
county_info4 = county_info3.sort_values(by='County')
county_info4

,County,State,TotalPop,povertyPercent,IncomePerCap,ID
0,Abbeville County,South Carolina,24788,22.663628,19234.247176,99c90f9d-1121-4b35-84eb-56b469dcf20e
1,Acadia Parish,Louisiana,62607,21.630767,21590.908876,5d79bf79-854a-4b9d-914a-04eac03271c8
2,Accomack County,Virginia,32840,19.905271,24265.653959,1680228e-cd63-4412-8c99-b8ea0ae2eeab
3,Ada County,Idaho,435117,11.909603,31642.314649,ee02e15f-6b20-4045-84e3-499c555c6013
4,Adair County,Iowa,74069,25.991018,20032.832791,d85f680f-ba5e-417a-b911-3118785dce7c
...,...,...,...,...,...,...
1950,Yukon-Koyukuk Census Area,Alaska,5453,25.492573,21057.054282,de3ba675-bda4-46ce-a361-75da03ed9d20
1951,Yuma County,Arizona,214390,19.415183,20796.998008,ba552f25-e155-468e-8efb-0fdc5b8e1bac
1952,Zapata County,Texas,14415,34.052820,17816.874853,efaa4a00-877e-4639-9a87-f00f4aba4f8f
1953,Zavala County,Texas,12152,36.275560,13104.867182,6b963f76-79c1-4bb5-9db0-c403ae14fde9
1954,Ziebach County,South Dakota,2837,43.100000,13461.000000,899137e1-7c1b-4def-8466-7a92594d6dcb

In [4]:
import pandas as pd
import uuid

covid_path = 'C:/Users/Mr. Grinch/Downloads/Data/COVID_county_data.csv'

covid_df = pd.read_csv(covid_path, usecols=['state', 'date', 'county', 'cases', 'deaths'])

# Convert 'date' column to datetime format
covid_df['date'] = pd.to_datetime(covid_df['date'])

covid_df['month'] = covid_df['date'].dt.month_name()
covid_df['year'] = covid_df['date'].dt.year

covid_monthly = covid_df.groupby(['county', 'month', 'year']).agg({
    'state': 'first',
    'cases': lambda x: x.iloc[-1] - x.iloc[0],
    'deaths': lambda x: x.iloc[-1] - x.iloc[0],
}).reset_index()

covid_monthly['county'] = covid_monthly['county'].str.split().str[0].str.lower()

# Convert county names to lowercase and match only the first word
county_info3['County'] = county_info3['County'].str.split().str[0].str.lower()

covid_monthly = pd.merge(covid_monthly, county_info3[['County', 'ID']], left_on='county', right_on='County', how='left')

# Drop the 'County' column as it's no longer needed
covid_monthly = covid_monthly.drop(columns=['County'])

covid_monthly

,county,month,year,state,cases,deaths,ID
0,abbeville,April,2020,South Carolina,27,0.0,99c90f9d-1121-4b35-84eb-56b469dcf20e
1,abbeville,August,2020,South Carolina,130,3.0,99c90f9d-1121-4b35-84eb-56b469dcf20e
2,abbeville,December,2020,South Carolina,303,3.0,99c90f9d-1121-4b35-84eb-56b469dcf20e
3,abbeville,February,2021,South Carolina,326,5.0,99c90f9d-1121-4b35-84eb-56b469dcf20e
4,abbeville,January,2021,South Carolina,568,4.0,99c90f9d-1121-4b35-84eb-56b469dcf20e
...,...,...,...,...,...,...,...
33799,ziebach,June,2020,South Dakota,1,0.0,899137e1-7c1b-4def-8466-7a92594d6dcb
33800,ziebach,May,2020,South Dakota,0,0.0,899137e1-7c1b-4def-8466-7a92594d6dcb
33801,ziebach,November,2020,South Dakota,99,5.0,899137e1-7c1b-4def-8466-7a92594d6dcb
33802,ziebach,October,2020,South Dakota,45,2.0,899137e1-7c1b-4def-8466-7a92594d6dcb
33803,ziebach,September,2020,South Dakota,14,0.0,899137e1-7c1b-4def-8466-7a92594d6dcb

In [5]:

def search_county(county_name):
    return covid_monthly[covid_monthly['county'] == county_name]

malheur_info = search_county('malheur')
print(malheur_info)

        county      month  year   state  cases  deaths  \
13740  malheur      April  2020  Oregon      7     0.0
13741  malheur     August  2020  Oregon    516    10.0
13742  malheur   December  2020  Oregon    495     6.0
13743  malheur   February  2021  Oregon     70     2.0
13744  malheur    January  2021  Oregon    345     6.0
13745  malheur       July  2020  Oregon    522     8.0
13746  malheur       June  2020  Oregon     76     1.0
13747  malheur      March  2020  Oregon      0     0.0
13748  malheur        May  2020  Oregon     22     0.0
13749  malheur   November  2020  Oregon    424     6.0
13750  malheur    October  2020  Oregon    316     8.0
13751  malheur  September  2020  Oregon    461    11.0

                                         ID
13740  81271b91-ed82-4898-9cc5-03d3a324663b
13741  81271b91-ed82-4898-9cc5-03d3a324663b
13742  81271b91-ed82-4898-9cc5-03d3a324663b
13743  81271b91-ed82-4898-9cc5-03d3a324663b
13744  81271b91-ed82-4898-9cc5-03d3a324663b
13745  81271b91-ed82-4898-9cc5-03d3a324663b
13746  81271b91-ed82-4898-9cc5-03d3a324663b
13747  81271b91-ed82-4898-9cc5-03d3a324663b
13748  81271b91-ed82-4898-9cc5-03d3a324663b
13749  81271b91-ed82-4898-9cc5-03d3a324663b
13750  81271b91-ed82-4898-9cc5-03d3a324663b
13751  81271b91-ed82-4898-9cc5-03d3a324663b

In [6]:
import pandas as pd

# Group by 'County' in county_info3 DataFrame to get population, poverty, and income data
county_summary = county_info3.groupby('County').agg({
    'ID': 'first',  
    'TotalPop': 'first',  
    'povertyPercent': 'first', 
    'IncomePerCap': 'first'  
}).reset_index()


covid_summary = covid_monthly.groupby('county').agg({
    'cases': 'sum',  # Total cases
    'deaths': 'sum'  # Total deaths
}).reset_index()

COVID_summary = pd.merge(county_summary, covid_summary, left_on='County', right_on='county', how='left')

COVID_summary['TotalCasesPer100K'] = ((COVID_summary['cases'] / COVID_summary['TotalPop']) * 100000).round(2)
COVID_summary['TotalDeathsPer100K'] = ((COVID_summary['deaths'] / COVID_summary['TotalPop']) * 100000).round(2)

# Drop the redundant 'county' column
COVID_summary.drop(columns=['county'], inplace=True)

COVID_summary

,County,ID,TotalPop,povertyPercent,IncomePerCap,cases,deaths,TotalCasesPer100K,TotalDeathsPer100K
0,abbeville,99c90f9d-1121-4b35-84eb-56b469dcf20e,24788,22.663628,19234.247176,2131.0,34.0,8596.90,137.16
1,acadia,5d79bf79-854a-4b9d-914a-04eac03271c8,62607,21.630767,21590.908876,5859.0,179.0,9358.38,285.91
2,accomack,1680228e-cd63-4412-8c99-b8ea0ae2eeab,32840,19.905271,24265.653959,2448.0,34.0,7454.32,103.53
3,ada,ee02e15f-6b20-4045-84e3-499c555c6013,435117,11.909603,31642.314649,44967.0,418.0,10334.46,96.07
4,adair,d85f680f-ba5e-417a-b911-3118785dce7c,74069,25.991018,20032.832791,9367.0,60.0,12646.32,81.01
...,...,...,...,...,...,...,...,...,...
1807,yukon-koyukuk,de3ba675-bda4-46ce-a361-75da03ed9d20,5453,25.492573,21057.054282,324.0,4.0,5941.68,73.35
1808,yuma,ba552f25-e155-468e-8efb-0fdc5b8e1bac,214390,19.415183,20796.998008,-136361.0,-2965.0,-63604.18,-1382.99
1809,zapata,efaa4a00-877e-4639-9a87-f00f4aba4f8f,14415,34.052820,17816.874853,1606.0,24.0,11141.17,166.49
1810,zavala,6b963f76-79c1-4bb5-9db0-c403ae14fde9,12152,36.275560,13104.867182,1749.0,35.0,14392.69,288.02
1811,ziebach,899137e1-7c1b-4def-8466-7a92594d6dcb,2837,43.100000,13461.000000,334.0,9.0,11773.00,317.24

In [7]:

# Function to search for specific counties
def search_county(county_name):
    return COVID_summary[COVID_summary['County'] == county_name]

# Search for Shelby County
malheur_info = search_county('malheur')
print(malheur_info)

washington_info = search_county('washington')
print(washington_info)

loudoun_info = search_county('loudoun')
print(loudoun_info)

harlan_info = search_county('harlan')
print(harlan_info)

       County                                    ID  TotalPop  povertyPercent  \
1021  malheur  81271b91-ed82-4898-9cc5-03d3a324663b     30421       24.298225

      IncomePerCap   cases  deaths  TotalCasesPer100K  TotalDeathsPer100K
1021  17567.504323  3254.0    58.0           10696.56              190.66
          County                                    ID  TotalPop  \
1714  washington  f1d03149-51ef-4293-936d-56d92a1de0e3   2564646

      povertyPercent  IncomePerCap     cases  deaths  TotalCasesPer100K  \
1714        12.49138  31477.494308  117104.0   946.0            4566.09

      TotalDeathsPer100K
1714               36.89
      County                                    ID  TotalPop  povertyPercent  \
990  loudoun  7ee79381-a25e-44cf-a285-6c1bd9ddafe9    374558        3.689598

     IncomePerCap    cases  deaths  TotalCasesPer100K  TotalDeathsPer100K
990  50455.645745  21789.0   188.0            5817.26               50.19
     County                                    ID  TotalPop  povertyPercent  \
732  harlan  d6440a57-4a36-436a-981f-28aa39536a96     31017         33.1229

     IncomePerCap   cases  deaths  TotalCasesPer100K  TotalDeathsPer100K
732  16678.064062 -5487.0  -125.0           -17690.3              -403.0